import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import QueryProvider from "./QueryProvider";
import { cookies } from 'next/headers';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Project api next",
  description: "Generated by create next app",
  icons: {
    icon: "/poke.png", 
  },
};


export default function RootLayout({children,
}: Readonly<{
  children: React.ReactNode;
}>)
{
  const cookieStore = cookies();
  const session = cookieStore.get('session');
  const username = session?.value || ''; 
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <Navbar />
        </nav>
        <QueryProvider>
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
